spring.application.name=HRManagerAPI
spring.datasource.url=jdbc:postgresql://localhost:5433/hrmanager
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=makara
spring.security.user.password=12345678
jwt.secret=bW9yZV9zZWN1cmVfc2VjcmV0X2tleV9oZXJlX3JhbmRvbQ==
logging.level.org.springframework.security=DEBUG